<?php

namespace App\Modules\Billing\Enums;

enum SubscriptionEventType: string
{
    case SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED';
    case TRIAL_STARTED = 'TRIAL_STARTED';
    case TRIAL_ENDED = 'TRIAL_ENDED';
    case INVOICE_GENERATED = 'INVOICE_GENERATED';
    case PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED';
    case PAYMENT_FAILED = 'PAYMENT_FAILED';
    case SUBSCRIPTION_SUSPENDED = 'SUBSCRIPTION_SUSPENDED';
    case SUBSCRIPTION_REACTIVATED = 'SUBSCRIPTION_REACTIVATED';
    case SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED';
}
